name: example
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  diff_image2:
    path: ../
  image: ^4.1.3

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

assets:
  - assets/