name: example
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  diff_image:
    path: ../../diff_image
  image: ^4.0.17

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

assets:
  - assets/