name: diff_image
description: A package to get the difference between two images. Currently supports fetching images from web and from local memory.
version: 1.0.2
homepage: https://github.com/limonadev/diff_image

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  http: ^1.1.0
  image: ^4.0.17
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
